project_name: cmdb

builds:
  - main: ./cmd/qdsl
    id: qdsl
    binary: qdsl
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.release={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0

nfpms:
  - id: qdsl
    file_name_template: "qdsl-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    package_name: qdsl
    maintainer: listware
    description: QDSL
    license: "Apache 2.0"
    bindir: /usr/bin
    builds:
      - qdsl
    formats:
      - rpm
      - deb
    contents: []
